# Secrets configuration placeholder
development:
  secret_key_base: 'your-development-secret-key'

test:
  secret_key_base: 'your-test-secret-key'

production:
  secret_key_base: 'your-production-secret-key'
